<a href="https://colab.research.google.com/github/MagdaSousa/Estudos_Numpy/blob/main/NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 

NumPy é uma biblioteca de álgebra linear para Python

In [24]:
import numpy as np

## Criando NumPy Arrays

Criando um array numpy, apartir de uma lista python

In [25]:
minha_lista = [1,2,3]
np.array(minha_lista)

array([1, 2, 3])

In [26]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos incorporados (Built-in Methods)


### arange

Retorna valores uniformemente espaçados dentro de um determinado intervalo.

In [27]:
np.arange(0,14)# cria uma sequencia de números

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [28]:
np.arange(0,13,3)# cria uma sequencia de números pulando de 2 em 2

array([ 0,  3,  6,  9, 12])

### zeros e ones

Gerar matrizes de zeros ou de ums

In [29]:
np.zeros(3)# criando array de zeros

array([0., 0., 0.])

In [30]:
np.zeros((5,5))# criar matris 5x5 zerada

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.ones(3)# matriz preenchida com números 1

array([1., 1., 1.])

In [32]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Retorna números uniformemente espaçados ao longo de um intervalo especificado.  
Parâmetros obrigatórios  
start: O valor inicial da sequência.  
end: O valor final da sequência, a menos que o ponto final seja definido como   False.



In [33]:
np.linspace(0,10,3)# semelhante ao arenge, start,stop, quantos números vc quer ver espaçados

array([ 0.,  5., 10.])

In [34]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Cria uma matriz identidade  



In [35]:
np.eye(4)# contem 1 na diagonal e zero no restante

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
### rand
Cria uma matriz da forma dada e preencha com amostras aleatórias de uma distribuição uniforme sobre ``[0, 1)``.

In [36]:
np.random.rand(2)# especifica o parametro para criar números com a mesma probabilidade de serem selecionados

array([0.01613402, 0.52896637])

In [37]:
np.random.rand(5,5)# matriz de duas dimensoes

array([[0.71905066, 0.07073309, 0.48658473, 0.68614813, 0.22648418],
       [0.88224546, 0.52160815, 0.29675422, 0.47642205, 0.25791827],
       [0.77288828, 0.99643941, 0.7246696 , 0.48386735, 0.73487572],
       [0.5791119 , 0.46633243, 0.29207819, 0.70717853, 0.58213218],
       [0.47522788, 0.73203851, 0.51334309, 0.44499371, 0.28011204]])

### randn

Retorna uma amostra (ou amostras) da distribuição "normal". Ao contrário de rand, que é uniforme:

In [38]:
np.random.randn(2)

array([-1.37557868,  0.50972631])

In [39]:
np.random.randn(5,5)

array([[ 0.51517017,  0.30857542, -0.98474751, -0.24883493,  0.16539058],
       [ 0.88393306,  0.24311197,  1.91855261,  0.57208523,  1.21423013],
       [-1.52860095,  1.7246447 , -0.51617757, -2.05844146,  0.28429345],
       [-0.28498482,  0.17463026,  0.43357607,  1.99628395, -0.2360663 ],
       [ 1.00117949,  0.61953035, -0.89489821,  0.08884049,  0.16925134]])

### randint
Retorna inteiros aleatórios de "low" (inclusive) para "high" (exclusivo).

In [40]:
np.random.randint(1,100)

10

In [41]:
np.random.randint(1,100,10)

array([ 3, 71,  6, 36,  1, 23,  5, 53, 20, 24])

## Atributos de Array e Métodos

Vamos discutir alguns atributos e métodos úteis ou uma matriz:

In [42]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
ranarr

array([19,  1,  7, 24, 47,  9,  9, 26, 12,  3])

## Reshape
Retorna uma matriz contendo os mesmos dados com uma nova forma.

In [45]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos, ou para encontrar seus locais de índice usando argmin ou argmax

In [46]:
ranarr

array([19,  1,  7, 24, 47,  9,  9, 26, 12,  3])

In [47]:
ranarr.max()

47

In [48]:
ranarr.argmax()

4

In [49]:
ranarr.min()

1

In [50]:
ranarr.argmin()

1

## Shape:

In [51]:
# Vector
arr.shape

(25,)

In [52]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [53]:
arr.reshape(1,25).shape

(1, 25)

In [58]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [55]:
arr.reshape(25,1).shape

(25, 1)

### dtype
tipo dos dados

In [56]:
arr.dtype

dtype('int64')